# Generated by Django 6.0.6 on 2026-06-18 00:36

import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=productos.models.generar_code, max_length=32, unique=True)),
                ('titulo', models.CharField(max_length=50)),
                ('foto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=20)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('Juguetes para niños', 'Juguetes'), ('Decoración general', 'Decoración'), ('Piezas de repuesto', 'Repuestos'), ('Juegos de mesa', 'Juegos'), ('Pokemones de uso carios', 'Pokemon')], max_length=50)),
            ],
        ),
    ]
