# Generated by Django 6.0.6 on 2026-06-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_orden_ordenitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
